version: '3'

services:

  front-proxy:
    image: nginx
    container_name: front-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - "/var/www/mellowdy_v2_front/nginx/mellowdy-front.conf:/etc/nginx/conf.d/mellowdy.conf:ro"
      - "/var/www/mellowdy_v2_front/nginx/certbot/www:/var/www/certbot/:ro"
      - "/var/www/mellowdy_v2_front/nginx/certbot/conf/:/etc/nginx/ssl/:ro"
      - "/var/www/mellowdy_v2_front/frontend-static-files:/usr/share/nginx/html"
    depends_on:
      - frontend
    networks:
      -  mellowdy-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - "/var/www/mellowdy_v2_front/nginx/certbot/www/:/var/www/certbot/:rw"
      - "/var/www/mellowdy_v2_front/nginx/certbot/conf/:/etc/letsencrypt/:rw"
    networks:
      -  mellowdy-network
      
volumes:
  frontend-static-files:

networks:
  mellowdy-network:
    name: mellowdy-network
    driver: bridge
