FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 8080

# TODO: Should add env variable
ENV VITE_MELLOWDY_API_URL=${VITE_MELLOWDY_API_URL}

CMD ["npm", "run", "dev"]